version: '3'

services:
  snippet-service:
    container_name: "snippet-service-infra"
    image: ghcr.io/ing-sistemas/snippet-service:dev@sha256:169d40534d303942e67e63a1efe67a603fb8eeac563e6f81b0928e59ea715464
    ports:
      - "8081:8081"
    env_file:
        - .env

  snippet-db:
    container_name: "snippet-db-infra"
    image: postgres:12
    ports:
      - "5433:5433"
    env_file:
        - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_SNIPPET}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  permission-service:
    container_name: "permission-service-infra"
    image: ghcr.io/ing-sistemas/permission-service:dev@sha256:235c0ac7e1fcaf357d76ff2dee89f32c805daff99dade1aee0e8e0bbb7b1c419
    ports:
      - "8080:8080"
    env_file:
        - .env

  permission-db:
    container_name: "permission-db-infra"
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
        - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_PERMISSION}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  printscript-service:
    container_name: "printscript-service-infra"
    image: ghcr.io/ing-sistemas/printscript-service:dev@sha256:0cdfb14c5d366e0239402ea8c834c282dc07adcc25857a48a1f48c8563403448
    ports:
      - "8082:8082"
    env_file:
        - .env

  ui:
    container_name: "ui-infra"
    image:
    ports:
        - "8083:8083"
    env_file:
      - .env

#  nginx:
#    container_name: nginx
#    restart:
#    image: nginx
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot

  proxy:
    container_name: "reverse-proxy"
    image: nginx
    ports:
      - "8083:80"
    volumes:
      - ./static/:/usr/share/nginx/html:ro
      - ./conf.d:/etc/nginx/conf.d:ro


#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    command: certonly --webroot -w /var/www/certbot --force-renewal --email {} -d {print-script} --agree-tos