#do not merge to main branch
      #redis
services:
    azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        container_name: "azurite"
        hostname: azurite
        restart: always
        ports:
            - "10000:10000"
            - "10001:10001"
            - "10002:10002"
        volumes:
            - blob:/workspace

    redis:
        container_name: "event-bus"
        image: redis:6-alpine
        ports:
            - "6379:6379"

volumes:
    blob:
        external: false