#do not merge to main branch
      #redis
services:
  snippet-service:
    container_name: "snippet-service-infra"
    image: ghcr.io/ing-sistemas/snippet-service:dev-latest
    ports:
      - "8081:8081"
    env_file:
      - .env

  snippet-db:
    container_name: "snippet-db-infra"
    image: postgres:12
    ports:
      - "5433:5433"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_SNIPPET}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  permission-service:
    container_name: "permission-service-infra"
    image: ghcr.io/ing-sistemas/permission-service:dev-latest
    ports:
      - "8080:8080"
    env_file:
      - .env

  permission-db:
    container_name: "permission-db-infra"
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_PERMISSION}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  printscript-service:
    container_name: "printscript-service-infra"
    image: ghcr.io/ing-sistemas/printscript-service:dev-latest
    ports:
      - "8082:8082"
    env_file:
      - .env

  azure:
    container_name: "asset-service-infra"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "${ASSET_PORT}:${ASSET_PORT}"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset-service"
      NEW_RELIC_AGENT_ENABLED: false

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite-infra"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace


  redis:
      container_name: "event-bus-infra"
      image: redis:6-alpine
      
      ports:
           - "6379:6379"

volumes:
  pgdata:
  blob:
      external: false
